---
- include_role:
    name: galaxy/geerlingguy.nginx

- name: Creates shared folder
  file: 
    path: /home/{{ deploy_user }}/consul/shared
    state: directory    
    owner: deploy
    group: wheel
    mode: 0755

- name: Creates shared config folder
  file: 
    path: /home/{{ deploy_user }}/consul/shared/config
    state: directory    
    owner: deploy
    group: wheel
    mode: 0755

- name: Creates shared environment folder
  file: 
    path: /home/{{ deploy_user }}/consul/shared/config/environments
    state: directory    
    owner: deploy
    group: wheel
    mode: 0755

- name: Copy secrets configuration to shared folder
  command: cp /home/{{ deploy_user }}/consul/config/secrets.yml /home/{{ deploy_user }}/consul/shared/config/secrets.yml

- name: Copy database configuration to shared folder
  command: cp /home/{{ deploy_user }}/consul/config/database.yml /home/{{ deploy_user }}/consul/shared/config/database.yml

- name: Copy production environment configuration to shared folder
  command: cp /home/{{ deploy_user }}/consul/config/environments/production.rb /home/{{ deploy_user }}/consul/shared/config/environments/production.rb

- name: Copy unicorn.rb template for capistrano to shared folder
  become_user: deploy
  template:
    src: "{{ playbook_dir }}/roles/capistrano/templates/unicorn.rb"
    dest: /home/deploy/consul/shared/config/unicorn.rb
    owner: deploy
    group: wheel

- name: Create Unicorn folders
  file:
    path: "/home/deploy/consul/shared/{{ item }}"
    state: directory
    owner: deploy
    group: wheel
    mode: 0775
  with_items:
    - "pids" 
    - "sockets" 
    - "log"

- name: Update Nginx template for capistrano
  become: true
  become_method: sudo
  template:
    src: "{{ playbook_dir }}/roles/capistrano/templates/consul_vhost.conf"
    dest: /etc/nginx/sites-enabled/default
    owner: deploy
    group: wheel
  notify: restart nginx

- name: Restart nginx
  become: true
  service: name=nginx state=restarted